# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170905_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhadepesquisa',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 18, 7, 33, 40, 884610)),
        ),
    ]
