# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170919_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 19, 9, 10, 44, 201676)),
        ),
    ]
