# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170919_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contanto', 'verbose_name_plural': 'Contato'},
        ),
        migrations.AddField(
            model_name='contato',
            name='celular',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='lugar',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='nomeadmin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='membros',
            field=models.ManyToManyField(related_name='projetos', to='blog.Membro'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 19, 9, 57, 48, 500220)),
        ),
    ]
