# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170919_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 19, 10, 3, 16, 688699)),
        ),
    ]
