# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170919_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nomeadmin',
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 19, 10, 6, 16, 857942)),
        ),
    ]
