# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170919_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinhaDePesquisa', models.CharField(max_length=255)),
                ('historia', models.TextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 21, 18, 21, 43, 463395)),
        ),
    ]
