# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170921_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 21, 18, 25, 59, 290332)),
        ),
    ]
